// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ],
  endPointUrl: 'https://www.thecocktaildb.com/api/json/v1/1',
  endPoints: {
    cocktailUrl: '/filter.php?g=Cocktail_glass',
    detailLookupUrl: '/lookup.php?',
  }
};
